name: Utils for workflow
description: Utility actons for github
inputs:   
  workflow-file:
    description: 'workflow file to use'
    required: true   
  status:
    description: 'status of workflow'  
  event:
    description: 'event that trigger de wf'
  branch:
    branch: 'event that trigger de wf'
outputs:
  run_id: 
    description: Run id
    value: ${{steps.wait_for_workflow.outputs.result}}
runs:
    using: 'composite'           
    steps:       
      - name: Wait for the student's workflow to complete   
        id: wait_for_workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = '${{ inputs.workflow-file }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflows = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id: workflow,
                  per_page: 1,
                  status: '${{ inputs.status }}',
                  event:  '${{ inputs.event }}',
                  branch:  '${{ inputs.branch }}'
                });          
            const run = workflows.data.workflow_runs[0];                
            return run.id;
          result-encoding: string
