name: Utils for workflow
description: Utility actons for github
inputs:   
  workflow-file:
    description: 'workflow file to use'
    required: true   
outputs:
  run_id: 
    description: Run id
    value: ${{steps.wait_for_workflow.outputs.result}}
runs:
    using: 'composite'           
    steps:       
      - name: Wait for the student's workflow to complete   
        id: wait_for_workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = '${{ inputs.workflow-file }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflow,
              per_page: 1
            });
            const run = workflows.data.workflow_runs[0];
            if (run.status !== 'completed') {
              core.setFailed('The workflow did not complete in time.');
            }            
            return run.id;
          result-encoding: string
